ITSRunning.WebApp/Controllers/TrainingController.cs
using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.ServiceBus;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using ITSRunning.WebApp.Models;
using ITSRunning.WebApp.Models.TrainingViewModels;
using ITSRunning.DataAccess.Activities;
using ITSRunning.Models.Requests;
using ITSRunning.DataAccess.Telemetries;
using ITSRunning.Models.Models;
using System.Collections.Generic;

namespace ITSRunning.WebApp.Controllers
{
    public class TrainingController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _configuration;
        private readonly IActivityRepository _activityRepository;
        private readonly ITelemetryRepository _telemetryRepository;

        public TrainingController(
            UserManager<ApplicationUser> userManager,
            IConfiguration configuration,
            IActivityRepository activityRepository,
            ITelemetryRepository telemetryRepository)
        {
            _userManager = userManager;
            _configuration = configuration;
            _activityRepository = activityRepository;
            _telemetryRepository = telemetryRepository;
        }
        /*
        [Authorize]
        public ActionResult Index()
        {
            var activities = _activityRepository.GetByTypeAndUsername(1, User.Identity.Name);
            return View(activities);
            /* use async method and get response with signalr
            try
            {
                var listTraining = new ListTrainingRequest()
                {
                    RunnerUsername = User.Identity.Name
                };
                await SendCommand(listTraining);
            }
            catch
            {
            }
            return View();
            */
        //}

        [Authorize]
        public ActionResult Index(int id)
        {
            var activities = _activityRepository.GetByTypeAndUsername(1, User.Identity.Name);
            ViewData["id"] = id;
            return View(activities);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            var telemetries = _telemetryRepository.GetAll(id);
            return View(telemetries);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Training/Create
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(TrainingCreation training)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newTraining = new NewTrainingRequest()
                    {
                        RunnerUsername = User.Identity.Name,
                        Name = training.Name,
                        Location = training.Location,
                        Date = DateTime.Now
                    };
                    await SendCommand(newTraining);
                    return RedirectToAction(nameof(Index),0);
                }
                else
                {
                    return View(training);
                }
            }
            catch
            {
                return View(training);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult StartTraining(int id)
        {
            try
            {
                return RedirectToAction("Run", "Runner", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Training/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var deleteTraining = new DeleteActivityRequest()
                {
                    Username = User.Identity.Name,
                    IdActivity = id
                };
                await SendCommand(deleteTraining);
                return RedirectToAction("Run", "Runner", new { id = id });
            }
            catch
            {
                return RedirectToAction(nameof(Index), new { id = id });
            }
        }

        public async Task SendCommand<TCommand>(TCommand command)
        {
            string serviceBusConnectionString = _configuration["ConnectionStrings:ServiceBus"];
            string queueName = _configuration["ServiceBusQueueName"];
            IQueueClient queueClient = new QueueClient(serviceBusConnectionString, queueName);
            var messageBody = JsonConvert.SerializeObject(command);
            var message = new Message(Encoding.UTF8.GetBytes(messageBody));
            await queueClient.SendAsync(message);
            await queueClient.CloseAsync();
        }
    }
}

ITSRunning.WebApp/Views/Training/Create.cshtml
@model ITSRunning.Models.Requests.NewTrainingRequest

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>TrainingData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    <script src="~/js/geoLocation.js"></script>
    <script>
        $(function () {
            getAddressFromLatLon();
        });
    </script>
}

ITSRunning.WebApp/Views/Training/Details.cshtml
@model IEnumerable<ITSRunning.Models.Telemetries.TelemetryDetails>
@{
    ViewData["Title"] = "Details";
}

@section Styles {
    <link rel="stylesheet" href="https://atlas.microsoft.com/sdk/css/atlas.min.css?api-version=1.0" type="text/css" />
    <link rel="stylesheet" href="~/css/runner.css" />
}

<h2>Details</h2>
<div id="map">

</div>

@section Scripts{
    <script src="https://atlas.microsoft.com/sdk/js/atlas.min.js?api-version=1.0"></script>
    <script src="~/js/geoLocation.js"></script>
    <script>
        var data = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model));
        drawActivity(data);
    </script>
}

ITSRunning.WebApp/Views/Training/Index.cshtml
@model IEnumerable<ITSRunning.Models.Models.Activity>

@{
    ViewData["Title"] = "Index";
    int idActivity = (int) ViewData["id"];
}

<h2>Trainings:</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.Id == idActivity)
            {
                continue;
            }
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td style="text-align:right;">
                    @if (item.State == 0)
                    {
                        @Html.ActionLink("Start", "StartTraining", new { id = item.Id });
                        @(" | ")
                    }
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>


























@*@{
        ViewData["Title"] = "Trainings";
    }

    <h2>Training list:</h2>

    <p>
        <a asp-controller="Training" asp-action="Create">Create New</a>
    </p>
    <table class="table table-striped" id="trainings">
        <thead>
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Created</th>
                <th>State</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
    @section Scripts
        {
        <script src="~/lib/signalr/browser/signalr.js"></script>
        <script type="text/javascript">
            $(function () {
                var topicListener =
                    new signalR
                        .HubConnectionBuilder()
                        .withUrl("/topiclistener")
                        .build();

                topicListener.start().then(() => {
                    //topicListener.invoke("Register", "@@User.Identity.Name");
                });
                topicListener.on("ListTrainingResponse", (args) => {
                    var table = $("#trainings");
                    var tbody = table.find("tbody");

                    tbody.empty();

                    $(args).each((i, item) => {
                        console.log(i);
                        if (args[i].state == 0) {
                            var a = "<a data-id='" + args[i].id + "' href='#' class='btn btn-default startTrain'>Start</a>";
                            a += " | <a data-id='" + args[i].id + "' href='#' class='btn btn-default detailTrain'>Detail</a>";
                            a += " | <a data-id='" + args[i].id + "' href='#' class='btn btn-default deleteTrain'>Delete</a>";
                        } else {
                            var a = "<a data-id='" + args[i].id + "' href='#' class='btn btn-default detailTrain'>Detail</a>";
                            a += " | <a data-id='" + args[i].id + "' href='#' class='btn btn-default deleteTrain'>Delete</a>";
                        }
                        tbody.append("<tr><td>" + args[i].name + "</td><td>" + args[i].location + "</td><td>" + args[i].creationDate + "</td><td>" + a + "</td></tr>");
                    });

                    $("a.startTrain").click(function (e) {
                        var id = $(e.target).data("id");
                        var url = '@Url.Action("StartTraining", new { id = "__id__" })'.replace("__id__", id);
                        window.location.href = url;
                    });
                    $("a.detailTrain").click(function (e) {
                        var id = $(e.target).data("id");
                        var url = '@Url.Action("Details", new { id = "__id__" })'.replace("__id__", id);
                        window.location.href = url;
                    });
                    $("a.deleteTrain").click(function (e) {
                        var id = $(e.target).data("id");
                        var url = '@Url.Action("Delete", new { id = "__id__" })'.replace("__id__", id);
                        window.location.href = url;
                    });
                });
            });
        </script>
    }*@